workspace:
  base: /go
  path: src/github.com/gauravbansal74/drone-build

pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      # Disabled: main.go:99: cli.StringSlice composite literal uses unkeyed fields
      # - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  publish:
    image: gauravbansal74/drone-build
    repo: gauravbansal74/drone-build
    # tags: [ "latest" ]
    secrets: [ gauravbansal74, gbansal74 ]
    when:
      branch: master
      event: push