workspace:
  base: /go
  path: src/github.com/gauravbansal74/drone-build

pipeline:
  information:
    image: golang:1.8
    commands: sh ./ci/build.sh   

  server:
    image: golang:1.8
    commands:
      - go get
      - go build
      - go test

  publish:
    image: plugins/docker
    repo:  gauravbansal74/drone-build
    commands: 
      - ls
    # tags: 
    tags: ${DRONE_COMMIT_SHA:0:8}
    username: gauravbansal74
    password: gbansal74
    # secrets: ["gauravbansal74", "gbansal74"]
    when:
      branch: master
      event: push   
