workspace:
  base: /go
  path: src/github.com/gauravbansal74/drone-build

pipeline:
  test:
    image: golang:1.8
    commands:
      - go get -u github.com/drone/drone-ui/dist
      - go get -u golang.org/x/tools/cmd/cover
      - go test -cover $(go list ./... | grep -v /vendor/)

  server:
    image: golang:1.8
    commands:
      - go get
      - go build
      - go test
      
  build:
    image: golang:1.8
    commands: sh ./ci/build.sh   

  publish:
    image: plugins/docker
    repo:  gauravbansal74/drone-build
    commands: 
      - echo ${DRONE_TAG}
    # tags: ${DRONE_COMMIT_SHA:0:8}
    tags: ${DRONE_TAG##v}
    username: gauravbansal74
    password: gbansal74
    # secrets: ["gauravbansal74", "gbansal74"]
    when:
      branch: master
      event: push   
